name: Print Message Workflow

on:
  push:
    branches:
      - CJ-gha.yml
  workflow_dispatch: # Enables manual trigger
    inputs:
      message: 
        description: "Enter the message to print" 
        required: true 
        default: "Hello, World!" # Default value

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Message
        run: echo "${{ inputs.message }}"

